apiVersion: metering.openshift.io/v1
kind: ReportDataSource
metadata:
  labels:
    operator-metering: "true"
  name: custom-role-node-capacity-cpu-cores
spec:
  prometheusMetricsImporter:
    query: |
      ((kube_node_status_capacity_cpu_cores * on(node) group_left(provider_id) max(kube_node_info) by (node, provider_id)) * on(node) group_left (role) kube_node_role{role='worker'}) * on(node) group_right(provider_id, role) kube_node_labels
