apiVersion: metering.openshift.io/v1
kind: Report
metadata:
  name: custom-role-node-cpu-capacity-hourly
  namespace: openshift-metering
spec:
  query: custom-role-node-cpu-capacity-labels 
  reportingStart: "2020-09-15T10:00:00+08:00"
  schedule:
    period: "hourly"
